### ISSUE TITLE
Failed to Convert PMML 

### ISSUE THREAD

**Issue by junchenfeng** [jpmml/jpmml-statsmodels#1]
I ran into the following error message:
```
java.lang.IllegalArgumentException: Attribute 'statsmodels.base.data.PandasData._cache.xnames' not set
	at org.jpmml.python.PythonObject.get(PythonObject.java:69)
	at org.jpmml.python.PythonObject.getList(PythonObject.java:258)
	at org.jpmml.python.PythonObject.getList(PythonObject.java:262)
	at statsmodels.data.ModelData$Cache.getXNames(ModelData.java:134)
	at statsmodels.data.ModelData.toSchema(ModelData.java:53)
	at statsmodels.regression.RegressionResults.encodePMML(RegressionResults.java:47)
	at statsmodels.regression.RegressionResultsWrapper.encodePMML(RegressionResultsWrapper.java:34)
	at org.jpmml.statsmodels.Main.run(Main.java:127)
	at org.jpmml.statsmodels.Main.main(Main.java:93)

Exception in thread "main" java.lang.IllegalArgumentException: Attribute 'statsmodels.base.data.PandasData._cache.xnames' not set
	at org.jpmml.python.PythonObject.get(PythonObject.java:69)
	at org.jpmml.python.PythonObject.getList(PythonObject.java:258)
	at org.jpmml.python.PythonObject.getList(PythonObject.java:262)
	at statsmodels.data.ModelData$Cache.getXNames(ModelData.java:134)
	at statsmodels.data.ModelData.toSchema(ModelData.java:53)
	at statsmodels.regression.RegressionResults.encodePMML(RegressionResults.java:47)
	at statsmodels.regression.RegressionResultsWrapper.encodePMML(RegressionResultsWrapper.java:34)
	at org.jpmml.statsmodels.Main.run(Main.java:127)
	at org.jpmml.statsmodels.Main.main(Main.java:93)
```
Here are the ENV info:

java : 
openjdk@15, maven@3.3. maven clean install returned success.

Python 3.7.10, 
pandas==1.2.2
statsmodels==0.12.2

**Comment by vruusmann** [comment]
> maven clean install returned success.

The project contains integration tests (executed during `mvn clean install`) that were generated using statsmodels 0.11.1.

Looks like StatsModels have changed their data structures between 0.11 and 0.12 significantly.

**Comment by vruusmann** [comment]
I've now updated my environment to the following:
Python 3.7(.2)
Pandas 1.2.3
StatsModels 0.12.2

The re-generated integration tests also pass cleanly. This leads me to think that the original exception is about something else than Python package version mismatch.

@junchenfeng Can you provide a simple reproducibl example about your modeling task? Which StatsModels model type are you using, how is it parameterized?

**Comment by vruusmann** [comment]
All JPMML-StatsModels integration tests pass cleanly with the current StatsModels reference version of 0.13(.5).

Therefore, marking this issue as "fixed".
